import type { Area, AreaKey, Tenant } from "@/types";

/**
 * 7エリア（本部 stores_area タクソノミーに対応）。
 * color は「LIFE IS COLORFUL」レインボーパレットから割り当て。
 */
export const AREAS: Area[] = [
  { key: "hokkaido-tohoku", name: "北海道・東北", color: "#91c2e1" },
  { key: "hokuriku-shinetsu", name: "北陸・信越", color: "#a4d2de" },
  { key: "kanto", name: "関東", color: "#8cc63f" },
  { key: "tokai", name: "東海", color: "#c6d876" },
  { key: "kansai", name: "関西", color: "#ed1c24" },
  { key: "shikoku-chugoku", name: "四国・中国", color: "#ea5c52" },
  { key: "kyushu-okinawa", name: "九州・沖縄", color: "#e6b8c4" },
];

/**
 * 移行対象の加盟店18店（07c §9 で確定）。
 * 連絡先・住所・紹介文・FAX・SNSは各店の「UNSTANDARD専用サイト」公開ページ
 * （schema.org / JSON-LD・フッター）から取得（2026-06-02時点）。
 */
export const TENANTS: Tenant[] = [
  // 北海道・東北
  {
    slug: "housingfukushimacenter",
    name: "ハウジング福島センター",
    shortName: "ハウジング福島センター",
    area: "hokkaido-tohoku",
    prefecture: "福島県",
    city: "郡山市菜根",
    street: "５丁目4-16",
    postalCode: "963-8862",
    tel: "0120-726-063",
    fax: "024-505-4230",
    description: "福島県郡山市の工務店で規格住宅を建てるなら、ハウジング福島センターにお任せください。モノとしての家ではなく、毎日を楽しむ”場”を作りたい。自分たちの”好き”やライフスタイルに合ったこれまでのスタンダードとは違う価値をつくる、UNSTANDARD(アンスタンダード)に加盟しています。",
    legacyUrl: "https://unstandard-members.com/housingfukushimacenter/",
  },
  // 関東
  {
    slug: "onfleekhome",
    name: "On Fleek Home",
    shortName: "On Fleek Home",
    area: "kanto",
    prefecture: "埼玉県",
    city: "熊谷市代",
    street: "723-1",
    postalCode: "360-0804",
    tel: "048-598-7004",
    fax: "048-598-7074",
    social: { instagram: "https://www.instagram.com/onfleekhome.jp?igsh=MTkzN25kYnIyaTFsaQ==" },
    description: "埼玉県熊谷市の工務店で規格住宅を建てるなら、On Fleek Homeにお任せください。モノとしての家ではなく、毎日を楽しむ”場”を作りたい。自分たちの”好き”やライフスタイルに合ったこれまでのスタンダードとは違う価値をつくる、UNSTANDARD(アンスタンダード)に加盟しています。",
    legacyUrl: "https://unstandard-members.com/onfleekhome/",
  },
  {
    slug: "woodplan",
    name: "株式会社ウッドプラン ENJOY HOUSE",
    shortName: "ウッドプラン ENJOY HOUSE",
    area: "kanto",
    prefecture: "群馬県",
    city: "高崎市上佐野町",
    street: "824-3",
    postalCode: "370-0857",
    tel: "027-326-2348",
    fax: "027-384-3391",
    social: { instagram: "https://www.instagram.com/woodplan_takasaki/", youtube: "https://youtube.com/channel/UClHlO0sNil0gN3S3Ad_rErg?si=KNaHod8UpPEGfMLH", tiktok: "https://www.tiktok.com/@enjoyhouse2004" },
    description: "群馬県高崎市の工務店で規格住宅を建てるなら、株式会社ウッドプラン　ENJOY HOUSEにお任せください。モノとしての家ではなく、毎日を楽しむ”場”を作りたい。自分たちの”好き”やライフスタイルに合ったこれまでのスタンダードとは違う価値をつくる、UNSTANDARD(アンスタンダード)に加盟しています。",
    legacyUrl: "https://unstandard-members.com/woodplan/",
  },
  {
    slug: "itakura",
    name: "株式会社板倉商事",
    shortName: "板倉商事",
    area: "kanto",
    prefecture: "千葉県",
    city: "大網白里市駒込",
    street: "491-5",
    postalCode: "299-3235",
    tel: "0475-72-8885",
    fax: "0475-72-8875",
    description: "千葉県大網の工務店で規格住宅を建てるなら、株式会社板倉商事にお任せください。モノとしての家ではなく、毎日を楽しむ”場”を作りたい。自分たちの”好き”やライフスタイルに合ったこれまでのスタンダードとは違う価値をつくる、UNSTANDARD(アンスタンダード)に加盟しています。",
    legacyUrl: "https://unstandard-members.com/itakura/",
  },
  {
    slug: "kuusou-koubou",
    name: "株式会社空創工房",
    shortName: "空創工房",
    area: "kanto",
    prefecture: "神奈川県",
    city: "中郡大磯町",
    street: "国府新宿593-5",
    postalCode: "259-0112",
    tel: "0463-71-9330",
    fax: "0463-71-4939",
    social: { instagram: "https://www.instagram.com/kuusoukoubou/", facebook: "https://www.facebook.com/kuusou.k" },
    description: "神奈川県中郡大磯町の工務店で規格住宅を建てるなら、株式会社空創工房にお任せください。モノとしての家ではなく、毎日を楽しむ”場”を作りたい。自分たちの”好き”やライフスタイルに合ったこれまでのスタンダードとは違う価値をつくる、UNSTANDARD(アンスタンダード)に加盟しています。",
    legacyUrl: "https://unstandard-members.com/kuusou-koubou/",
  },
  {
    slug: "woodbox-yamanashi",
    name: "スマトチ スヴァーリエヒュース株式会社",
    shortName: "WOODBOX山梨",
    area: "kanto",
    prefecture: "山梨県",
    city: "中央市若宮",
    street: "8-6",
    postalCode: "409-3803",
    tel: "055-274-4777",
    social: { instagram: "https://www.instagram.com/sumatochi/", facebook: "https://www.facebook.com/swehus", youtube: "https://www.youtube.com/channel/UCNDJCeH_3_G-naBm4xSRWAg", tiktok: "https://www.tiktok.com/@sumatochi" },
    description: "山梨県中央市の工務店で規格住宅を建てるなら、スマトチ スヴァーリエヒュース株式会社にお任せください。モノとしての家ではなく、毎日を楽しむ”場”を作りたい。自分たちの”好き”やライフスタイルに合ったこれまでのスタンダードとは違う価値をつくる、UNSTANDARD(アンスタンダード)に加盟しています。",
    legacyUrl: "https://unstandard-members.com/woodbox-yamanashi/",
  },
  {
    slug: "hilaki",
    name: "WOODBOX海老名 株式会社 建築のひら木",
    shortName: "WOODBOX海老名（建築のひら木）",
    area: "kanto",
    prefecture: "神奈川県",
    city: "海老名市中新田",
    street: "2-12-31-1F",
    postalCode: "243-0422",
    tel: "046-240-8951",
    social: { instagram: "https://www.instagram.com/hilaki_ecol/", facebook: "https://ja-jp.facebook.com/%E6%A0%AA%E5%BC%8F%E4%BC%9A%E7%A4%BE%E3%81%B2%E3%82%89%E6%9C%A8%E3%82%BC%E3%83%AD%E3%82%A8%E3%83%8D%E4%BD%8F%E5%AE%85%E5%B7%A5%E5%8B%99%E5%BA%97-207731265935913/", youtube: "https://www.youtube.com/channel/UCTxBeM0QHlt0D1my-pIVw5g" },
    description: "神奈川県海老名市の工務店で規格住宅を建てるなら、WOODBOX海老名 株式会社 建築のひら木にお任せください。モノとしての家ではなく、毎日を楽しむ”場”を作りたい。自分たちの”好き”やライフスタイルに合ったこれまでのスタンダードとは違う価値をつくる、UNSTANDARD(アンスタンダード)に加盟しています。",
    legacyUrl: "https://unstandard-members.com/hilaki/",
  },
  // 北陸・信越
  {
    slug: "flash",
    name: "フラッシュ株式会社",
    shortName: "フラッシュ（UNSTANDARD富山中央店）",
    area: "hokuriku-shinetsu",
    prefecture: "富山県",
    city: "富山市黒瀬",
    street: "59-1",
    postalCode: "939-8213",
    tel: "076-413-8077",
    fax: "076-493-8801",
    social: { facebook: "https://www.facebook.com/profile.php?id=61585238691053" },
    description: "富山県富山市の工務店で規格住宅を建てるなら、UNSTANDARD富山中央店にお任せください。モノとしての家ではなく、毎日を楽しむ”場”を作りたい。自分たちの”好き”やライフスタイルに合ったこれまでのスタンダードとは違う価値をつくる、UNSTANDARD(アンスタンダード)に加盟しています。",
    legacyUrl: "https://unstandard-members.com/flash/",
  },
  {
    slug: "tsujiya_archt",
    name: "辻家株式会社",
    shortName: "辻家",
    area: "hokuriku-shinetsu",
    prefecture: "石川県",
    city: "金沢市四十万町北ル",
    street: "10-1",
    postalCode: "921-8133",
    tel: "076-225-4228",
    social: { instagram: "https://www.instagram.com/tsujiya_archt/" },
    description: "石川県金沢市の工務店で規格住宅を建てるなら、辻家株式会社にお任せください。モノとしての家ではなく、毎日を楽しむ”場”を作りたい。自分たちの”好き”やライフスタイルに合ったこれまでのスタンダードとは違う価値をつくる、UNSTANDARD(アンスタンダード)に加盟しています。",
    legacyUrl: "https://unstandard-members.com/tsujiya_archt/",
  },
  {
    slug: "hiraokakensetu",
    name: "株式会社平岡建設",
    shortName: "平岡建設",
    area: "hokuriku-shinetsu",
    prefecture: "福井県",
    city: "小浜市和久里",
    street: "20-8-1",
    postalCode: "917-0024",
    tel: "0770-56-1725",
    fax: "0770-56-5550",
    social: { instagram: "https://www.instagram.com/hiraoka_inc?igsh=MWdkZDc2enYybmZtOA%3D%3D&#038;utm_source=qr" },
    description: "福井県小浜市の工務店で規格住宅を建てるなら、株式会社平岡建設にお任せください。モノとしての家ではなく、毎日を楽しむ”場”を作りたい。自分たちの”好き”やライフスタイルに合ったこれまでのスタンダードとは違う価値をつくる、UNSTANDARD(アンスタンダード)に加盟しています。",
    legacyUrl: "https://unstandard-members.com/hiraokakensetu/",
  },
  // 東海
  {
    slug: "nawa-kenchiku",
    name: "株式会社名和建築",
    shortName: "名和建築",
    area: "tokai",
    prefecture: "岐阜県",
    city: "岐阜市茜部野瀬",
    street: "3丁目200番地",
    postalCode: "500-8283",
    tel: "058-271-4612",
    social: { instagram: "https://www.instagram.com/nawa.kentiku?igsh=cWJqNXRhbDdtOHVt", facebook: "https://www.facebook.com/profile.php?id=61553783927421" },
    description: "岐阜県各務原市の工務店で規格住宅を建てるなら、株式会社名和建築にお任せください。モノとしての家ではなく、毎日を楽しむ”場”を作りたい。自分たちの”好き”やライフスタイルに合ったこれまでのスタンダードとは違う価値をつくる、UNSTANDARD(アンスタンダード)に加盟しています。",
    legacyUrl: "https://unstandard-members.com/nawa-kenchiku/",
  },
  {
    slug: "harmony",
    name: "株式会社HARMONY",
    shortName: "HARMONY",
    area: "tokai",
    prefecture: "三重県",
    city: "津市藤方",
    street: "1036-1",
    postalCode: "514-0815",
    tel: "059-273-5445",
    social: { instagram: "https://www.instagram.com/harmonyshizensozainoie/", facebook: "https://www.facebook.com/shizensozainoie.co.jp/", twitter: "https://twitter.com/HARMONY81809634" },
    description: "三重県津市の工務店で規格住宅を建てるなら、株式会社HARMONYにお任せください。モノとしての家ではなく、毎日を楽しむ”場”を作りたい。自分たちの”好き”やライフスタイルに合ったこれまでのスタンダードとは違う価値をつくる、UNSTANDARD(アンスタンダード)に加盟しています。",
    legacyUrl: "https://unstandard-members.com/harmony/",
  },
  // 関西
  {
    slug: "soubi-kenchiku-kikaku",
    name: "アトリエSumika-住処- 株式会社創美建築企画",
    shortName: "アトリエSumika（創美建築企画）",
    area: "kansai",
    prefecture: "京都府",
    city: "京都市伏見区南寝小屋町",
    street: "53番地",
    postalCode: "612-8379",
    tel: "075-603-1022",
    fax: "075-603-1023",
    social: { instagram: "https://www.instagram.com/atoriesumika/" },
    description: "京都市伏見区の工務店で規格住宅を建てるなら、アトリエＳｕｍｉｋａ-住処- 株式会社創美建築企画にお任せください。モノとしての家ではなく、毎日を楽しむ”場”を作りたい。自分たちの”好き”やライフスタイルに合ったこれまでのスタンダードとは違う価値をつくる、UNSTANDARD(アンスタンダード)に加盟しています。",
    legacyUrl: "https://unstandard-members.com/soubi-kenchiku-kikaku/",
  },
  {
    slug: "woodbox-osaka",
    name: "WOODBOX OSAKA 株式会社市兵衛",
    shortName: "WOODBOX OSAKA（市兵衛）",
    area: "kansai",
    prefecture: "大阪府",
    city: "和泉市はつが野",
    street: "1丁目44番5",
    postalCode: "594-1106",
    tel: "0725-53-5850",
    description: "大阪府和泉市の工務店で規格住宅を建てるなら、株式会社市兵衛にお任せください。モノとしての家ではなく、毎日を楽しむ”場”を作りたい。自分たちの”好き”やライフスタイルに合ったこれまでのスタンダードとは違う価値をつくる、UNSTANDARD(アンスタンダード)に加盟しています。",
    legacyUrl: "https://unstandard-members.com/woodbox-osaka/",
  },
  // 四国・中国
  {
    slug: "kaitaku",
    name: "有限会社開拓",
    shortName: "開拓",
    area: "shikoku-chugoku",
    prefecture: "鳥取県",
    city: "鳥取市大覚寺",
    street: "170-55",
    postalCode: "680-0863",
    tel: "0857-22-6120",
    fax: "0857-23-6540",
    description: "鳥取県鳥取市の工務店で規格住宅を建てるなら、有限会社開拓にお任せください。モノとしての家ではなく、毎日を楽しむ”場”を作りたい。自分たちの”好き”やライフスタイルに合ったこれまでのスタンダードとは違う価値をつくる、UNSTANDARD(アンスタンダード)に加盟しています。",
    legacyUrl: "https://unstandard-members.com/kaitaku/",
  },
  {
    slug: "kindwork",
    name: "カインドワーク株式会社",
    shortName: "カインドワーク",
    area: "shikoku-chugoku",
    prefecture: "高知県",
    city: "四万十市一条通",
    street: "5丁目10-22",
    postalCode: "781-8131",
    tel: "0880-34-8297",
    fax: "0880-34-8298",
    social: { instagram: "https://www.instagram.com/kindwork.10.01?igshid=amY3YjkzYWhkdXdh" },
    description: "高知県四万十市の工務店で規格住宅を建てるなら、カインドワーク株式会社にお任せください。モノとしての家ではなく、毎日を楽しむ”場”を作りたい。自分たちの”好き”やライフスタイルに合ったこれまでのスタンダードとは違う価値をつくる、UNSTANDARD(アンスタンダード)に加盟しています。",
    legacyUrl: "https://unstandard-members.com/kindwork/",
  },
  // 九州・沖縄
  {
    slug: "arcathhome",
    name: "株式会社ARCATH HOME",
    shortName: "ARCATH HOME",
    area: "kyushu-okinawa",
    prefecture: "熊本県",
    city: "熊本市南区御幸西",
    street: "2丁目3番3号",
    postalCode: "861-4171",
    tel: "0963-78-5005",
    fax: "0963-78-5006",
    social: { instagram: "https://www.instagram.com/arcath_home", facebook: "https://www.facebook.com/share/1MiJFWiYeA/?mibextid=wwXIfr", youtube: "https://www.youtube.com/@ARCATHHOME-mm7lg" },
    description: "熊本県熊本市の工務店で規格住宅を建てるなら、株式会社ARCATH HOMEにお任せください。モノとしての家ではなく、毎日を楽しむ”場”を作りたい。自分たちの”好き”やライフスタイルに合ったこれまでのスタンダードとは違う価値をつくる、UNSTANDARD(アンスタンダード)に加盟しています。",
    legacyUrl: "https://unstandard-members.com/arcathhome/",
  },
  {
    slug: "den-kenchiku",
    name: "有限会社田建築工房",
    shortName: "田建築工房",
    area: "kyushu-okinawa",
    prefecture: "鹿児島県",
    city: "鹿児島市紫原",
    street: "7丁目5-20",
    postalCode: "890-0082",
    tel: "099-250-6347",
    social: { instagram: "https://www.instagram.com/denkenchiku/?hl=ja", facebook: "https://www.facebook.com/people/%E6%9C%89%E9%99%90%E4%BC%9A%E7%A4%BE%E7%94%B0%E5%BB%BA%E7%AF%89%E5%B7%A5%E6%88%BF/100054675060626/", youtube: "https://www.youtube.com/channel/UCaQ2k4v7BNe73SUw-xuw1MA" },
    description: "鹿児島県鹿児島市の工務店で規格住宅を建てるなら、有限会社田建築工房にお任せください。モノとしての家ではなく、毎日を楽しむ”場”を作りたい。自分たちの”好き”やライフスタイルに合ったこれまでのスタンダードとは違う価値をつくる、UNSTANDARD(アンスタンダード)に加盟しています。",
    legacyUrl: "https://unstandard-members.com/den-kenchiku/",
  },
];

export function getArea(key: AreaKey): Area {
  const area = AREAS.find((a) => a.key === key);
  if (!area) throw new Error(`Unknown area: ${key}`);
  return area;
}

export function tenantsByArea(key: AreaKey): Tenant[] {
  return TENANTS.filter((t) => t.area === key);
}

export function getTenant(slug: string): Tenant | undefined {
  return TENANTS.find((t) => t.slug === slug);
}
